### ISSUE TITLE
Version 1 schematic

### ISSUE THREAD

**Issue by JmanNZ** [freitz85/AppleIISd#11]
Hi
Could you please add the version 1 schematic. 

Thanks

**Comment by freitz85** [comment]
Hi, will re-add it in a later release for historic reference.
In the meantime you can access it in the repo's history: [Schematic](https://github.com/freitz85/AppleIISd/blob/bc75ba9eb68a1dbe6fbfc35a5bd47801bf60c525/AppleIISd.pdf)
