### ISSUE TITLE
Firmware does not set drive number when booting

### ISSUE THREAD

**Issue by rb6502** [freitz85/AppleIISd#5]
Hi Florian,

I've been working on supporting AppleIISd as an optional expansion card in the MAME emulator, and I've noticed that the boot firmware does not initialize zero page location $43 (what you call DSNUMBER).  The fill pattern we use in MAME to avoid issues with some buggy A2 games has $FF there, for instance, so GETBLOCK thinks we're looking for drive 2 and adds $10000 to the block number.  This probably causes weird problems on real hardware as well, since not all Apple IIs have clear RAM on a cold start, and $43 could contain anything on a Ctrl-Open Apple-Reset restart.

Cheers,
-RB

**Comment by freitz85** [comment]
Thank you, RB for this comment!
I remember being unsure if I should do anything with those ZP locations when I started this project. Do I need to clear all ZP locations used by my firmware or just $43? I originally thought it was only written to by ProDOS.

Some time ago, I too had the idea to "include" my card in an emulator, but I never came around to do so. This could make debugging some outstanding Smartport issues much easier. Maybe your fix and two others I found while working on my 6502 branch will get us a little further.

Regards, Florian

**Comment by rb6502** [comment]
ProDOS itself does initialize all of the ZP locations necessary, but when booting from the AppleIISd your slot firmware doesn't set all of the locations.  It's this code:

```
; load disk blocks 0 and 1 to $800 and $A00
@BOOT:      LDA   #$08        ; load to $800
            STA   BUFFER+1    ; buffer hi
            STZ   BUFFER      ; buffer lo
            STZ   BLOCKNUM+1  ; block hi
            STZ   BLOCKNUM    ; block lo
            JSR   READ
```

There needs to be an STZ DSNUMBER too.  My SDCard emulation needs more work before I can commit the support to MAME, but it already boots and runs Total Replay and various ProDOS 8-based images fine.  I suspect this may be what's causing issue #3.

**Comment by freitz85** [comment]
I have made changes to the code in 99eebeb89fe98dc47f60455a9ad6a9a5f8bd3eef. Please see if it works now.
Anyway, DSNUMBER being not initialized on boot is a nice bug and it is interesting to see that it worked in the first place ;-)

**Comment by rb6502** [comment]
I just tried it and it didn't work.  Looking at the disassembly, the setting of DSNUMBER is missing in the AppleIISd.bin firmware image.  Could you double-check what's going on?

Edit: Error was on my end, loading the correct binary now and it works.  You might suggest the people with issue #3 try out the new version too then.

**Comment by rb6502** [comment]
I've now pulled the tree and rebuilt the firmware and even though the LDA/STA are in the source, the generated AppleIISd.bin is still missing them.  I don't understand what's happening.

**Comment by freitz85** [comment]
I have just pushed another fix when I realized that BIT may not work in some situations.
Are you sure you are using the correct build_image.* from the Firmware folder to build the AppleIISd.bin file? If you used the one from the Software folder, this only builds the Flasher program.

I probably will change the whole build process to a CMake based one, with ROM code and flasher as subprojects. "Install" could then create the image for the flasher.

**Comment by rb6502** [comment]
Yeah, it was my error.  I forgot that our AT28C64B class actually saves the contents and uses those in preference to the original ROM image so that you can run the flasher and have it take effect.  With the latest firmware image it works fine in the emulation and properly sets DSNUMBER.

**Comment by OttHydromet** [comment]
Glad to hear that! I will close the issue

**Comment by freitz85** [comment]
Glad to hear that! I will close the issue.
