### ISSUE TITLE
Post to PCBWay Shared Projects?

### ISSUE THREAD

**Issue by dlxmax** [freitz85/AppleIISd#7]
I'm glad I found the AppleIISD and your blog as well, as this is exactly what I need for my IIe! Thanks.
One thing, would you mind posting it to PCBWay Shared Projects? That way anyone can order just one board at a very low price. I really don't need ten! It could also help promote the project. More people should know about this.

I would post it myself, but they give a 10% kickback on PCB sales to the poster, which really should be you.
Again, thanks for this. I look forward to building it!
https://www.pcbway.com/project/shareproject/

**Comment by freitz85** [comment]
Thank you for this suggestion, I will have a look into it. It sounds very interesting!
