### ISSUE TITLE
Replacement for 28C64

### ISSUE THREAD

**Issue by timmcross** [freitz85/AppleIISd#8]
Because these are so hard to find, I was thinking of using a 28C256.  I think it has the same pinout just 2 or 3 more address lines which I could pull high or low.

Also, I see the picture uses a -15 part.  Would a -25 part be too slow or is that fine for an IIe or IIgs?

Thanks!

**Comment by freitz85** [comment]
Thank you @timmcross, for the suggestion!
I compared the two chips and it should be possible to use both when the the two additional address lines are tied to ground. I will include this in upcoming hardware revisions.
Meanwhile it is possible to use two jumper wire to ground, as the pins were not connected yet.

Regarding the speed I will have to do some more digging, but I assume a slower one could be fine.

**Comment by timmcross** [comment]
I was able to ground out the extra address lines (A11 and A12 were already grounded, I added A13, A14 from the 28c256) and it seems to work fine.  I didn't try a -25 part however.  Thanks!
