### ISSUE TITLE
CPLD programming

### ISSUE THREAD

**Issue by timmcross** [freitz85/AppleIISd#9]
Sorry for an obvious question but after setting this project up from scratch, I think I am missing the part where the CPLD gets programmed.  I am having an issue with the flasher program (using a 28C256 but that is probably a different issue) but I assume that is only to flash the EEPROM?  I have been looking for the overall steps to set one of these up and I cannot find it.  Will flasher upload code to the EEPROM which will in turn flash the CPLD or does the CPLD need to be programmed separately?  Perhaps by a Raspberry PI and the included header on the board?  Thanks...

**Comment by timmcross** [comment]
So I took some time to google XC9572XL programming with a Raspberry PI and found a procedure to program one with xc3sprog.  I used a RPI v1 I had sitting around and programmed the VQ44 jed file you have in the repository.  After that, "flasher" completed and I was able to boot the card!  Great work!  Total Replay booted right up.  Thanks for developing this product!

**Comment by freitz85** [comment]
Sorry for answering late, I also wanted to suggest the RPi solution as I found the (knockoff-) Xilinx programers not to be very reliable.
I will add this information to the readme so that others can benefit from this. Thank you for bringing this to my attention.
